version: '3.1'

services:
  flask-htmx-prototype:
    build:
      context: ./
    environment:
      PYTHONUNBUFFERED: "true"
    ports:
      - "7777:7777"
    volumes:
      - ./:/src
    command: poetry run python app.py