DROP TABLE IF EXISTS albums;

CREATE TABLE albums (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	title TEXT NOT NULL,
	artist TEXT NOT NULL,
	is_recommended INTEGER NOT NULL
);
